### PR TITLE
Edit in relation to PR#1633 upstream

### PR DESCRIPTION
**Pull request by nimbinatus**
I adjusted the markdown, added the standard metadata, and adjusted the layout to follow the style guide for how-to articles. Please review and accept changes if you agree with them. Thanks!

### CODE REVIEW

**Comment by hikarutilmitt** [comment]
We need the screenshots retained, please.

**Comment by nimbinatus** [comment]
Fine by me! Renee told me that you'll be getting me the screenshots shortly. I'll add them in, recommit here, and then comment when it's ready.

**Comment by nimbinatus** [comment]
@hikarutilmitt , the images have been re-added. Please review and merge these changes to your branch if you agree with them, and then we can merge them upstream. Thanks!

**Comment by nimbinatus** [comment]
Fixed the rookie mistake, @hikarutilmitt . Please review and merge here if you agree, and then we can merge upstream. Thanks!

**Pull request merged**
