### PR TITLE
Edit in relation to PR#1635 in upstream

### PR DESCRIPTION
**Pull request by nimbinatus**
I adjusted the markdown, added the standard metadata, and tightened up the wording a bit. Please review and accept changes if you agree with them. Thanks!

### CODE REVIEW

**Comment by hikarutilmitt** [comment]
We need the screenshots retained, please.

**Comment by nimbinatus** [comment]
Fine by me! Renee told me that you'll be getting me the screenshots shortly. I'll add them in, recommit here, and then comment when it's ready.

**Comment by nimbinatus** [comment]
@hikarutilmitt , last one! The images have been re-added. Please review and merge to your branch if you agree with these changes, and then we can merge upstream. Thanks!

**Comment by nimbinatus** [comment]
Fixed the rookie mistake, @hikarutilmitt . Please review and merge here if you agree, and then we can merge upstream. Thanks!

**Comment by hikarutilmitt** [comment]
Great job on these so far! Thank you very much for the turnaround!

**Comment by nimbinatus** [comment]
You are very welcome! Please don't hesitate to reach out if you need more help :)

**Pull request merged**
